---
 - name: Do post-checks and render templates
   hosts: "{{ target }}"
   roles:
     - Juniper.junos
   connection: local
   gather_facts: no

   tasks:

      - name: Load merge from a file.
        juniper_junos_config:
          provider: "{{ provider_info }}"
          load: 'merge'
          src: "{{playbook_dir}}/{{ inventory_hostname }}.ifaces.conf"
        register: response
      - name: Print the complete response.
        debug:
          var: response

      - name: Do snapcheck for post-tests.
        juniper_junos_jsnapy:
          provider: "{{ provider_info }}"
          action: "snapcheck"
          dir: "./tests"
          test_files:
            - "post.yml"
          logfile: "jsnapy_tests.log"
        register: test_result

      - name: Verify JSNAPy tests pass
        assert:
          that:
            - "test_result.passPercentage == 100"
